<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCTUxp19\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCTUxp19/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCTUxp19.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCTUxp19\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCTUxp19\App_KernelDevDebugContainer([
    'container.build_hash' => 'CTUxp19',
    'container.build_id' => '6094abf3',
    'container.build_time' => 1654414044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCTUxp19');
