<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_service_log' => [[], ['_controller' => 'App\\Controller\\ServiceLogController::index'], [], [['text', '/service/log']], [], [], []],
    'get_count' => [[], ['_controller' => 'App\\Controller\\ServiceLogController::get_count'], [], [['text', '/count']], [], [], []],
];
